% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Oct-2025 14:42:35
%  MATLAB version: 25.1.0.3040723 (R2025a) Update 1
% -------------------------------------------------------------------
                                        

Ts = 5E-5;

Var = struct;
Var.Gain = 5;
Var.Offset = 3;

bessVoltage = 1500;

gfmInverter = struct;
%gfmInverter.apparentPower = 2e6;%2.2E+6;
gfmInverter.frequency = 60;
gfmInverter.DCVoltage = 1500;
gfmInverter.lineRMSVoltage = 690;
gfmInverter.SwitchFrequency = 10000;
gfmInverter.measurementSampleTime = 5E-5;
gfmInverter.droopControl = struct;
gfmInverter.droopControl.freqSlopeMp = 0.01;
gfmInverter.droopControl.lpfTimeConst = 0.015;
gfmInverter.droopControl.T2 = 0.006;
gfmInverter.droopControl.T1 = 0.005;
gfmInverter.droopControl.sampleTime = 5E-5;
gfmInverter.freqMeasTimeConst = 0.001;
gfmInverter.vsm = struct;
gfmInverter.vsm.inertiaConstant = 1;
gfmInverter.vsm.dampingCoefficent = 20;%10.056;
gfmInverter.vsm.freqDroop = 5;%10;
gfmInverter.vsm.PmeasTimeConst = 0.001;
gfmInverter.vsm.maxDampingPower = 0.9;
gfmInverter.vsm.minDampingPower = -0.6;
gfmInverter.vsm.samplingTime = 5E-5;
gfmInverter.vsm.dampingPowerFreqOption = ...
  'Use Grid Frequency Measurement';
gfmInverter.Qcontrol = struct;
gfmInverter.Qcontrol.voltageDroop = 5;%0.5;%;3;
gfmInverter.Qcontrol.QmeasTimeConst = 0.001;
gfmInverter.Qcontrol.voltageReference = 1;
gfmInverter.highSCRQControl = struct;
gfmInverter.highSCRQControl.voltageDroop = 0.3;
gfmInverter.highSCRQControl.QmeasTimeConst = 0.001;
gfmInverter.highSCRQControl.voltageReference = 1;
gfmInverter.ratedrmsCurrent = 577.35026918962581;
gfmInverter.L = 0.0001325;
gfmInverter.lineResistance = 0.08;
gfmInverter.currentLimit = struct;
gfmInverter.currentLimit.virImpResistanceCoeff = 0.1875;
gfmInverter.currentLimit.virImpXbyR = 13.2;
gfmInverter.currentLimit.viCurrentLimit = 1.2;
gfmInverter.currentLimit.viFilterTimeConst = 0.001;
gfmInverter.currentLimit.maxSaturationCurrent = 1.4;
gfmInverter.currentLimit.maxSaturationDelay = 0.001;
gfmInverter.currentLimit.satCurrentRunTime = 0.001;
gfmInverter.controller = struct;
gfmInverter.controller.CurrentControlSampleTime = 5E-5;
gfmInverter.controller.ctControllerKp = 2;
gfmInverter.controller.ctControllerKi = 10;
gfmInverter.controller.VoltageControlSampleTime = 5E-5;
gfmInverter.controller.voltControllerKp = 3;%3;
gfmInverter.controller.voltControllerKi = 1.5;%1.5;
gfmInverter.controller.voltageMaxId = 1.8;
gfmInverter.controller.voltageMinId = -1.8;
gfmInverter.controller.voltageMaxIq = 1.8;
gfmInverter.controller.voltageMinIq = -1.8;
gfmInverter.controller.voltMeasTimeConst = 0.005;

transformer = struct;
transformer.powerRating = 1000;
transformer.primaryRMSVoltage = 1000;
transformer.secondaryRMSVoltage = 13800;
transformer.PrimaryResistancePU = 0.02976;
transformer.SecondaryResistancePU = 0.01984;
transformer.PrimaryReactancePU = 0.07662;
transformer.SecondaryReactancePU = 0.11493;
transformer.ZeroSequenceReactancePU = 0.084282;

bessSystem.plantRating = 2000;%2200;
bessSystem.frequency = 50;
bessSystem.Vdc = 1500;
bessSystem.filterInductance = 1e-5;
bessSystem.filterResistance = 1e-3;
bessSystem.switchingFrequency = 20;
bessSystem.converterEfficiency = 100;
bessSystem.iMaxPU = 1.2;
bessSystem.activeDroop = 1e-4;
bessSystem.reactiveDroop = 0.02;
bessSystem.Vac = 690;

