% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Oct-2025 14:21:29
%  MATLAB version: 25.1.0.3040723 (R2025a) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('windTurbineMPPT.mat');

Ts = 5E-5;

Var = struct;
Var.Gain = 5;
Var.Offset = 3;

base = struct;
base.Vac = 4160;
base.power = 1.0E+7;
base.impedance = 1.73056;
base.Vdc = 1000;

pmsm = struct;
pmsm.pmax = 1.25E+7;
pmsm.Ld = 0.0016;
pmsm.Lq = 0.0016;
pmsm.Rs = 0.00082;
pmsm.fluxLinkage = 9;
pmsm.polePairs = 26;
pmsm.alpha = 6000;

powerCoefficient = saveVarsMat.powerCoefficient; % <1x1 struct> too many elements at powerCoefficient.Cp

windController = struct;
windController.kpVoltage = 0.2;
windController.kiVoltage = 2;
windController.kdVoltage = 0;
windController.kpId = 2;
windController.kiId = 100;
windController.kiIq = 100;
windController.kpIq = 2;
windController.kpMSC = 100;
windController.kiMSC = 1;

windSystem = struct;
windSystem.capacitance = 0.1;
windSystem.filterInductance = 0.001;
windSystem.dcBusCapacitance = 0.01;
windSystem.Vdc = 1500;
windSystem.iMaxPU = 1.2;
windSystem.frequency = 50;
windSystem.mpptPower = [0.059640018002074 0.11648757096719865 0.20128506075699973 ...
                        0.31966513773797167 0.477120144016592 0.67942710815348539 ...
                        0.93113068711379565 1.2252533607701455 1.5533034287532823 ...
                        ];
windSystem.plantRating = 1600;
windSystem.mpptWindSpeed = [4 5 6 7 8 9 10 11 12];
windSystem.converterEfficiency = 100;
windSystem.filterResistance = 0.001;
windSystem.Vac = 690;

windTurbine = saveVarsMat.windTurbine; % <1x1 struct> too many elements at windTurbine.cp

clear saveVarsMat;
